# Generated by Django 5.2.3 on 2025-06-22 06:57

import django.db.models.deletion
import django.utils.timezone
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(max_length=120, validators=[events.models.validate_slogan_length])),
                ('location', models.CharField(max_length=120, validators=[events.models.validate_location_length])),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('available_tickets', models.IntegerField(validators=[events.models.validate_available_tickets])),
                ('key_features', models.TextField(blank=True, null=True)),
                ('banner_url', models.URLField(blank=True, null=True)),
                ('organizer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='organizers.organizer')),
            ],
        ),
    ]
